#!/bin/bash
#
# Short:    Payload Handler Script - list the profile identifiers of all installed mobileconfigs
# Author:   Mark J Swift
# Version:  3.2.0
# Modified: 24-Oct-2020
#
# Called as follows:    
#   mobileconfig-list [user]
#
# A null user lists for the workstation.
# A non-null user lists for the specified user.
#
# This routine is used by gpupdate when processing mobileconfig files stored in a groups AD "Notes" field

# ---

sv_GPOuser="${1}"

# normal users can only handle their own configs.
if [ "$(whoami)" != "root" ]
then
  sv_GPOuser=""
fi

# ---

if [ -z "${sv_GPOuser}" ]
then
  profiles -L | grep "profileIdentifier:" | cut -d" " -f 4-
  
else
  profiles -L -U ${sv_GPOuser} | grep "profileIdentifier:" | cut -d" " -f 4-

fi

# ---

# Everything is OK
exit 0
