#!/bin/bash
#
# Short:    Payload Handler Script - print unique payload (managed) identifier from the specified mobileconfig (profile) file
# Author:   Mark J Swift
# Version:  3.2.0
# Modified: 24-Oct-2020
#
# Called as follows:    
#   mobileconfig-identifier <somefile.mobileconfig>
#
# This routine is used by gpupdate when processing mobileconfig files stored in a groups AD "Notes" field

# ---

sv_PayloadFilePath="${1}"

if test -z "${sv_PayloadFilePath}"
then
  echo "Usage mobileconfig-identifier <somefile.mobileconfig>"
  exit 0
fi

# ---

if test -e "${sv_PayloadFilePath}"
then
  # Get the mobileconfig payload identifier
  /usr/libexec/PlistBuddy 2>/dev/null -c "Print ':PayloadIdentifier'" "${sv_PayloadFilePath}"
fi

# ---

# Everything is OK
exit 0
