#!/bin/bash
#
# Short:    Payload Handler Script - install the specified mobileconfig (profile) file
# Author:   Mark J Swift
# Version:  3.2.3
# Modified: 02-Jan-2021
#
# Called as follows:    
#   mobileconfig-install <somefile.mobileconfig> [user]
#
# Without a user specified, installs for the workstation.
# With a user, installs for the specified user.
#
# This routine is used by gpupdate when processing mobileconfig files stored in a groups AD "Notes" field

# ---

# Calculate SystemVersionStampAsNumber

sv_SystemVersionStampAsString="$(sw_vers -productVersion)"
iv_SystemVersionStampAsNumber=0
for iv_Num in $(echo ${sv_SystemVersionStampAsString}".0.0.0.0" | cut -d"." -f1-4 | tr "." "\n")
do
  iv_SystemVersionStampAsNumber=$((${iv_SystemVersionStampAsNumber}*256+${iv_Num}))
done

# ---

if [ ${iv_SystemVersionStampAsNumber} -ge 184549376 ]
then
  iv_Err=99
  echo "Installing mobileconfigs administratively is not supported in MacOS 11 and later"
  exit ${iv_Err}
fi

# ---

# get command line options

sv_PayloadFilePath="${1}"

if test -z "${sv_PayloadFilePath}"
then
  echo "Usage mobileconfig-install <somefile.mobileconfig> [user]"
  exit 0
fi

sv_GPOuser="${2}"

if test -n "${sv_GPOuser}"
then
  # normal users can only handle their own configs.
  if [ "$(whoami)" != "root" ]
  then
    sv_GPOuser=""
  
  else
    if [ ${iv_SystemVersionStampAsNumber} -lt 168493056 ]
    then
      iv_Err=99
      echo "Installing mobileconfigs for other users is not supported prior to MacOS 10.11"
      exit ${iv_Err}
    fi
  fi
fi

# ---

# Get the mobileconfig payload identifier
sv_PayloadIdentifier=$(/usr/libexec/PlistBuddy 2>/dev/null -c "Print ':PayloadIdentifier'" "${sv_PayloadFilePath}" )

# ---

# Check if already installed

if test -z "${sv_GPOuser}"
then
  if test -n "$(profiles -L | grep "profileIdentifier:" | cut -d" " -f 4- | grep -E "^${sv_PayloadIdentifier}$")"
  then
    iv_Err=0
    echo "No need to install, profile already installed"
    exit ${iv_Err}
  fi  
  
else
  if test -n "$(profiles -L -U ${sv_GPOuser} | grep "profileIdentifier:" | cut -d" " -f 4- | grep -E "^${sv_PayloadIdentifier}$")"
  then
    iv_Err=0
    echo "No need to install, profile already installed"
    exit ${iv_Err}
  fi  
fi

# ---

sv_TempFilePath=""
if [ "$(whoami)" != "root" ]
then
  # make sure we can modify the file
  sv_TempFilePath="/tmp/$$.mobileconfig"
  cp -f "${sv_PayloadFilePath}" "${sv_TempFilePath}"
  sv_PayloadFilePath="${sv_TempFilePath}"
  
  # If we are a normal user, we shouldn't install anything that we cannot uninstall
  /usr/libexec/PlistBuddy -c "Delete ':PayloadRemovalDisallowed'" "${sv_PayloadFilePath}"
fi

# ---

# Install the mobileconfig
if test -z "${sv_GPOuser}"
then
  sv_Err=$(/usr/bin/profiles 2>&1 -I -F "${sv_PayloadFilePath}")
  iv_Err=$?
    
else
  sv_Err=$(/usr/bin/profiles 2>&1 -I -F "${sv_PayloadFilePath}" -U "${sv_GPOuser}")
  iv_Err=$?
  
fi

# ---

# Fish the actual error number out from inside the error message
if [ ${iv_Err} -ne 0 ]
then
  iv_ErrNo=$(echo "${sv_Err}" | grep -i " returned " | sed 's| returned ||' | tail -n1 | cut -d " " -f1)
  if test -n "${iv_ErrNo}"
  then
    iv_Err=${iv_ErrNo}
  fi
  echo "${sv_Err}"
  
else
  # Check if actually installed
  if test -z "${sv_GPOuser}"
  then
    if test -z "$(profiles -L | grep "profileIdentifier:" | cut -d" " -f 4- | grep -E "^${sv_PayloadIdentifier}$")"
    then
      iv_Err=98
      echo "Profile install failed"
    fi  
  
  else
    if test -z "$(profiles -L -U ${sv_GPOuser} | grep "profileIdentifier:" | cut -d" " -f 4- | grep -E "^${sv_PayloadIdentifier}$")"
    then
      iv_Err=98
      echo "Profile install failed"
    fi  
  fi

fi

# ---

# Tidy up
if [ -n "${sv_TempFilePath}" ]
then
  rm -f "${sv_TempFilePath}"
fi

# ---

exit ${iv_Err}
