#!/bin/bash
#
# Short:    Payload Handler Script - uninstall the mobileconfig (profile) with the specified profile identifier
# Author:   Mark J Swift
# Version:  3.2.3
# Modified: 02-Jan-2021
#
# Called as follows:
#   mobileconfig-uninstall <profileidentifier> [user]
#
# Without a user specified, uninstalls for the workstation.
# With a user, uninstalls for the specified user.
#
# This routine is used by gpupdate when processing mobileconfig files stored in a groups AD "Notes" field

# ---

# Calculate SystemVersionStampAsNumber

sv_SystemVersionStampAsString="$(sw_vers -productVersion)"
iv_SystemVersionStampAsNumber=0
for iv_Num in $(echo ${sv_SystemVersionStampAsString}".0.0.0.0" | cut -d"." -f1-4 | tr "." "\n")
do
  iv_SystemVersionStampAsNumber=$((${iv_SystemVersionStampAsNumber}*256+${iv_Num}))
done

# ---

if [ ${iv_SystemVersionStampAsNumber} -ge 184549376 ]
then
  iv_Err=99
  echo "Uninstalling profiles administratively is not supported in MacOS 11 and later"
  exit ${iv_Err}
fi

# ---

# get command line options

sv_PayloadIdentifier="${1}"

if test -z "${sv_PayloadIdentifier}"
then
  echo "Usage mobileconfig-uninstall <profileidentifier> [user]"
  exit 0
fi

sv_GPOuser="${2}"

if test -n "${sv_GPOuser}"
then
  # normal users can only handle their own configs.
  if [ "$(whoami)" != "root" ]
  then
    sv_GPOuser=""
  
  else
    if [ ${iv_SystemVersionStampAsNumber} -lt 168493056 ]
    then
      iv_Err=99
      echo "Uninstalling profiles for other users is not supported prior to MacOS 10.11"
      exit ${iv_Err}
    fi
  fi
fi

# ---

# Check if actually installed

if test -z "${sv_GPOuser}"
then
  if test -z "$(profiles -L | grep "profileIdentifier:" | cut -d" " -f 4- | grep -E "^${sv_PayloadIdentifier}$")"
  then
    iv_Err=0
    echo "No need to uninstall, profile not installed"
    exit ${iv_Err}
  fi  
  
else
  if test -z "$(profiles -L -U ${sv_GPOuser} | grep "profileIdentifier:" | cut -d" " -f 4- | grep -E "^${sv_PayloadIdentifier}$")"
  then
    iv_Err=0
    echo "No need to uninstall, profile not installed"
    exit ${iv_Err}
  fi  
fi

# ---

# Uninstall the mobileconfig
iv_Err=0

if test -z "${sv_GPOuser}"
then
  sv_Err=$(/usr/bin/profiles 2>&1 -R -p "${sv_PayloadIdentifier}")
  iv_Err=$?
  
else
  sv_Err=$(/usr/bin/profiles 2>&1 -R -p "${sv_PayloadIdentifier}" -U "${sv_GPOuser}")
  iv_Err=$?

fi

# ---

# Fish the actual error number out from inside the error message
if [ ${iv_Err} -ne 0 ]
then
  iv_ErrNo=$(echo "${sv_Err}" | grep -i " returned " | sed 's| returned ||' | tail -n1 | cut -d " " -f1)
  if test -n "${iv_ErrNo}"
  then
    iv_Err=${iv_ErrNo}
  fi

  # Special cases for errors that aren't errors
  case ${iv_Err} in
  -205)
    # Mobileconfig isn't installed, so no need to uninstall
    iv_Err=0
    ;;
    
  *)
    echo "${sv_Err}"
    ;;
 
  esac
  
else
  # Check if still installed
  if test -z "${sv_GPOuser}"
  then
    if test -n "$(profiles -L | grep "profileIdentifier:" | cut -d" " -f 4- | grep -E "^${sv_PayloadIdentifier}$")"
    then
      iv_Err=98
      echo "Profile uninstall failed"
    fi  
  
  else
    if test -n "$(profiles -L -U ${sv_GPOuser} | grep "profileIdentifier:" | cut -d" " -f 4- | grep -E "^${sv_PayloadIdentifier}$")"
    then
      iv_Err=98
      echo "Profile uninstall failed"
    fi  
  fi

fi

# ---

exit ${iv_Err}
